/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#0f1117",
        foreground: "#ffffff",
        card: "#1a1d29",
        "card-foreground": "#ffffff",
        popover: "#1a1d29",
        "popover-foreground": "#ffffff",
        primary: "#00d9ff",
        "primary-foreground": "#0f1117",
        secondary: "#252836",
        "secondary-foreground": "#ffffff",
        muted: "#2a2d3d",
        "muted-foreground": "#9ca3af",
        accent: "#00d9ff",
        "accent-foreground": "#0f1117",
        destructive: "#ff4757",
        "destructive-foreground": "#ffffff",
        border: "#2d3142",
        input: "#252836",
        ring: "#00d9ff",
        "chart-1": "#00d9ff",
        "chart-2": "#a855f7",
        "chart-3": "#10b981",
        "chart-4": "#f59e0b",
        "chart-5": "#ef4444",
        sidebar: "#0f1117",
        "sidebar-foreground": "#ffffff",
        "sidebar-primary": "#00d9ff",
        "sidebar-primary-foreground": "#0f1117",
        "sidebar-accent": "#1a1d29",
        "sidebar-accent-foreground": "#ffffff",
        "sidebar-border": "#2d3142",
        "sidebar-ring": "#00d9ff",
      },
      fontFamily: {
        sans: ['system-ui', 'Segoe UI', 'Roboto', 'Helvetica Neue', 'Arial', 'sans-serif'],
      },
      boxShadow: {
        'glow': '0 0 20px rgba(0, 217, 255, 0.3)',
        'glow-lg': '0 0 40px rgba(0, 217, 255, 0.4)',
      },
    },
  },
  plugins: [],
}
